[package]
name = "flatbox-doryen"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0.38"
parking_lot = "0.12.1"

flatbox = { path = "../flatbox", default-features = false }
doryen-rs = "1.3.0"